- name: apply ntp config
  hosts: My-Server
  tasks:

  roles:
    - common


- name: print out system outputs
  hosts: My-Server
  tasks:
    - shell: /sbin/chkconfig --list| grep ntp
      register: chkconfig_output

    - debug:
         msg="{{chkconfig_output}}"

    - local_action: copy content={{ chkconfig_output }} dest=/root/study/chkconfig.log
